In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# loading the dataset
df = pd.read_csv(r"C:\Users\Marshmellow\Downloads\ecommerce_sales_data.csv")
df

      Order Date Product Name     Category Region  Quantity  Sales   Profit
0     2024-12-31      Printer       Office  North         4   3640   348.93
1     2022-11-27        Mouse  Accessories   East         7   1197   106.53
2     2022-05-11       Tablet  Electronics  South         5   5865   502.73
3     2024-03-16        Mouse  Accessories  South         2    786   202.87
4     2022-09-10        Mouse  Accessories   West         1    509   103.28
...          ...          ...          ...    ...       ...    ...      ...
3495  2023-02-15      Monitor  Accessories  North         4   4064   771.16
3496  2022-09-18      Monitor  Accessories   East         1   1117   119.89
3497  2022-04-12       Laptop  Electronics  South         4    260    66.02
3498  2022-01-18      Printer       Office  South         3    222    50.28
3499  2024-11-01   Smartwatch  Electronics   East         9  10530  1777.32

[3500 rows x 7 columns]

-----------------------------------------------------------------------------------------------------------------
DATA CLEANING
-----------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------

In [3]:
df.head(30)

    Order Date Product Name     Category Region  Quantity  Sales   Profit
0   2024-12-31      Printer       Office  North         4   3640   348.93
1   2022-11-27        Mouse  Accessories   East         7   1197   106.53
2   2022-05-11       Tablet  Electronics  South         5   5865   502.73
3   2024-03-16        Mouse  Accessories  South         2    786   202.87
4   2022-09-10        Mouse  Accessories   West         1    509   103.28
5   2023-12-01       Camera  Electronics   West         1    524   106.35
6   2023-10-09   Headphones  Accessories  North         7   6167  1027.98
7   2022-01-14       Camera  Electronics  South         7   3059   873.50
8   2022-04-02   Smartwatch  Electronics   East         9   5526   595.28
9   2024-10-22      Printer       Office  South         8    672   186.37
10  2023-12-04      Monitor  Accessories  South         6   7074  1357.68
11  2022-09-27   Smartwatch  Electronics   East         2    502   137.40
12  2023-12-21       Tablet  Electronics  North         7   7462  2166.17
13  2024-02-03   Smartphone  Electronics   West         5   4205   585.29
14  2023-10-10       Camera  Electronics   West         1    570   138.54
15  2022-10-16   Headphones  Accessories   East         1    441   102.42
16  2022-05-15        Mouse  Accessories  North         7   7469   589.81
17  2023-02-11       Tablet  Electronics  South         2   2212   145.75
18  2023-12-27       Tablet  Electronics   East         5    740   146.39
19  2023-10-05   Headphones  Accessories  North         1    662   193.92
20  2024-03-05        Mouse  Accessories  North         7   5712   651.27
21  2023-07-18   Smartwatch  Electronics  North         3   2739   572.73
22  2023-06-25     Keyboard  Accessories   West         5   1400   213.63
23  2023-11-13      Printer       Office  North         3   3477   939.20
24  2022-07-09       Camera  Electronics  North         5   3475   570.36
25  2023-12-11       Laptop  Electronics   West         9   6138  1562.14
26  2023-03-18       Camera  Electronics   West         5   3665   406.93
27  2024-08-09      Printer       Office  North         2   2372   206.42
28  2024-05-04       Laptop  Electronics  North         2   1382   211.11
29  2022-09-04       Laptop  Electronics   West         1   1126   194.08

In [4]:
df.isnull().sum()

Order Date      0
Product Name    0
Category        0
Region          0
Quantity        0
Sales           0
Profit          0
dtype: int64

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df['Order Date'] = pd.to_datetime(df['Order Date'])
df

     Order Date Product Name     Category Region  Quantity  Sales   Profit
0    2024-12-31      Printer       Office  North         4   3640   348.93
1    2022-11-27        Mouse  Accessories   East         7   1197   106.53
2    2022-05-11       Tablet  Electronics  South         5   5865   502.73
3    2024-03-16        Mouse  Accessories  South         2    786   202.87
4    2022-09-10        Mouse  Accessories   West         1    509   103.28
...         ...          ...          ...    ...       ...    ...      ...
3495 2023-02-15      Monitor  Accessories  North         4   4064   771.16
3496 2022-09-18      Monitor  Accessories   East         1   1117   119.89
3497 2022-04-12       Laptop  Electronics  South         4    260    66.02
3498 2022-01-18      Printer       Office  South         3    222    50.28
3499 2024-11-01   Smartwatch  Electronics   East         9  10530  1777.32

[3500 rows x 7 columns]

In [7]:
df['Year'] = df['Order Date'].dt.year
df['Month'] = df['Order Date'].dt.month_name()
df

,Order Date,Product Name,Category,Region,Quantity,Sales,Profit,Year,Month
0,2024-12-31,Printer,Office,North,4,3640,348.93,2024,December
1,2022-11-27,Mouse,Accessories,East,7,1197,106.53,2022,November
2,2022-05-11,Tablet,Electronics,South,5,5865,502.73,2022,May
3,2024-03-16,Mouse,Accessories,South,2,786,202.87,2024,March
4,2022-09-10,Mouse,Accessories,West,1,509,103.28,2022,September
...,...,...,...,...,...,...,...,...,...
3495,2023-02-15,Monitor,Accessories,North,4,4064,771.16,2023,February
3496,2022-09-18,Monitor,Accessories,East,1,1117,119.89,2022,September
3497,2022-04-12,Laptop,Electronics,South,4,260,66.02,2022,April
3498,2022-01-18,Printer,Office,South,3,222,50.28,2022,January
3499,2024-11-01,Smartwatch,Electronics,East,9,10530,1777.32,2024,November

In [8]:
df.head(10)

,Order Date,Product Name,Category,Region,Quantity,Sales,Profit,Year,Month
0,2024-12-31,Printer,Office,North,4,3640,348.93,2024,December
1,2022-11-27,Mouse,Accessories,East,7,1197,106.53,2022,November
2,2022-05-11,Tablet,Electronics,South,5,5865,502.73,2022,May
3,2024-03-16,Mouse,Accessories,South,2,786,202.87,2024,March
4,2022-09-10,Mouse,Accessories,West,1,509,103.28,2022,September
5,2023-12-01,Camera,Electronics,West,1,524,106.35,2023,December
6,2023-10-09,Headphones,Accessories,North,7,6167,1027.98,2023,October
7,2022-01-14,Camera,Electronics,South,7,3059,873.50,2022,January
8,2022-04-02,Smartwatch,Electronics,East,9,5526,595.28,2022,April
9,2024-10-22,Printer,Office,South,8,672,186.37,2024,October

In [9]:
df.head(10)

,Order Date,Product Name,Category,Region,Quantity,Sales,Profit,Year,Month
0,2024-12-31,Printer,Office,North,4,3640,348.93,2024,December
1,2022-11-27,Mouse,Accessories,East,7,1197,106.53,2022,November
2,2022-05-11,Tablet,Electronics,South,5,5865,502.73,2022,May
3,2024-03-16,Mouse,Accessories,South,2,786,202.87,2024,March
4,2022-09-10,Mouse,Accessories,West,1,509,103.28,2022,September
5,2023-12-01,Camera,Electronics,West,1,524,106.35,2023,December
6,2023-10-09,Headphones,Accessories,North,7,6167,1027.98,2023,October
7,2022-01-14,Camera,Electronics,South,7,3059,873.50,2022,January
8,2022-04-02,Smartwatch,Electronics,East,9,5526,595.28,2022,April
9,2024-10-22,Printer,Office,South,8,672,186.37,2024,October

In [10]:
df.describe()

,Order Date,Quantity,Sales,Profit,Year
count,3500,3500.000000,3500.000000,3500.000000,3500.000000
mean,2023-07-13 00:53:53.828571648,4.931714,3047.966000,527.047203,2023.030857
min,2022-01-01 00:00:00,1.000000,51.000000,6.970000,2022.000000
25%,2022-10-16 18:00:00,3.000000,1049.500000,158.695000,2022.000000
50%,2023-07-21 12:00:00,5.000000,2350.500000,361.070000,2023.000000
75%,2024-04-16 06:00:00,7.000000,4537.000000,729.125000,2024.000000
max,2024-12-31 00:00:00,9.000000,10782.000000,2946.930000,2024.000000
std,NaN,2.575895,2440.213237,504.139732,0.809466

In [11]:
df.shape

(3500, 9)

In [12]:
df.columns

Index(['Order Date', 'Product Name', 'Category', 'Region', 'Quantity', 'Sales',
       'Profit', 'Year', 'Month'],
      dtype='object')

In [13]:
df.rename(columns={
    'Order Date': 'order_date', 'Product Name': 'product_name', 
    'Category': 'category', 'Region': 'region', 
    'Quantity': 'quantity', 'Sales': 'sales', 
    'Profit': 'profit', 'Year': 'year', 'Month': 'month'}, inplace=True )
df

,order_date,product_name,category,region,quantity,sales,profit,year,month
0,2024-12-31,Printer,Office,North,4,3640,348.93,2024,December
1,2022-11-27,Mouse,Accessories,East,7,1197,106.53,2022,November
2,2022-05-11,Tablet,Electronics,South,5,5865,502.73,2022,May
3,2024-03-16,Mouse,Accessories,South,2,786,202.87,2024,March
4,2022-09-10,Mouse,Accessories,West,1,509,103.28,2022,September
...,...,...,...,...,...,...,...,...,...
3495,2023-02-15,Monitor,Accessories,North,4,4064,771.16,2023,February
3496,2022-09-18,Monitor,Accessories,East,1,1117,119.89,2022,September
3497,2022-04-12,Laptop,Electronics,South,4,260,66.02,2022,April
3498,2022-01-18,Printer,Office,South,3,222,50.28,2022,January
3499,2024-11-01,Smartwatch,Electronics,East,9,10530,1777.32,2024,November

In [14]:
df.head(10)

,order_date,product_name,category,region,quantity,sales,profit,year,month
0,2024-12-31,Printer,Office,North,4,3640,348.93,2024,December
1,2022-11-27,Mouse,Accessories,East,7,1197,106.53,2022,November
2,2022-05-11,Tablet,Electronics,South,5,5865,502.73,2022,May
3,2024-03-16,Mouse,Accessories,South,2,786,202.87,2024,March
4,2022-09-10,Mouse,Accessories,West,1,509,103.28,2022,September
5,2023-12-01,Camera,Electronics,West,1,524,106.35,2023,December
6,2023-10-09,Headphones,Accessories,North,7,6167,1027.98,2023,October
7,2022-01-14,Camera,Electronics,South,7,3059,873.50,2022,January
8,2022-04-02,Smartwatch,Electronics,East,9,5526,595.28,2022,April
9,2024-10-22,Printer,Office,South,8,672,186.37,2024,October

In [17]:
df.to_csv(r"C:\Users\Marshmellow\Downloads\ecommerce_sales_data_cleaned.csv", index=False)
df

,order_date,product_name,category,region,quantity,sales,profit,year,month
0,2024-12-31,Printer,Office,North,4,3640,348.93,2024,December
1,2022-11-27,Mouse,Accessories,East,7,1197,106.53,2022,November
2,2022-05-11,Tablet,Electronics,South,5,5865,502.73,2022,May
3,2024-03-16,Mouse,Accessories,South,2,786,202.87,2024,March
4,2022-09-10,Mouse,Accessories,West,1,509,103.28,2022,September
...,...,...,...,...,...,...,...,...,...
3495,2023-02-15,Monitor,Accessories,North,4,4064,771.16,2023,February
3496,2022-09-18,Monitor,Accessories,East,1,1117,119.89,2022,September
3497,2022-04-12,Laptop,Electronics,South,4,260,66.02,2022,April
3498,2022-01-18,Printer,Office,South,3,222,50.28,2022,January
3499,2024-11-01,Smartwatch,Electronics,East,9,10530,1777.32,2024,November